# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: '<%= ENV['BROKER_USERNAME'] || "containers" %>'
  auth_password: '<%= ENV['BROKER_PASSWORD'] || "secret" %>'
  cookie_secret: 'e7247dae-a252-4393-afa3-2219c1c02efd'
  session_expiry: 86400

  cc_api_uri: 'http://api.vcap.me'
  external_ip: <%= ENV['DOCKER_HOST_IP'] || "127.0.0.1" %>
  external_host: <%= ENV['DOCKER_HOST_IP'] || "containers.vcap.me" %>

  ssl_enabled: false
  skip_ssl_validation: true

  host_directory: '/var/vcap/store/cf-containers-broker/'
  max_containers: 0
  allocate_docker_host_ports: true
  container_env_var_dir: '/var/vcap/store/cf-containers-broker/envdir'

  services:
  - name: 'postgresql96'
    id: 'ef761cec-14f7-11e7-8dfb-bbab51a4e12a'
    description: 'PostgreSQL 9.6 service for application development and testing'
    bindable: true
    tags: [postgresql96 postgresql sql relational]
    metadata:
      displayName: 'PostgreSQL 9.6'
      longDescription: 'A PostgreSQL 9.6 service for development and testing running inside a Docker container'
      providerDisplayName: 'Cloud Foundry Community'
      documentationUrl: 'https://github.com/frodenas/docker-postgresql'
      supportUrl: 'https://slack.cloudfoundry.org'
    plans:
    - id: 'f30f03fa-14f7-11e7-8d86-cf0d7f2c3728'
      name: 'free'
      description: 'Free Trial'
      container:
        backend: 'docker'
        image: 'frodenas/postgresql'
        tag: '9.6'
        persistent_volumes: [/data]
      credentials:
        username: {key: 'POSTGRES_USERNAME'}
        password: {key: 'POSTGRES_PASSWORD'}
        dbname: {key: 'POSTGRES_DBNAME'}
        uri: {prefix: 'postgres'}
  - name: 'redis32'
    id: '0fdcc9c0-14f5-11e7-9d8c-cfde16aa4822'
    description: 'Redis 3.2 service for application development and testing'
    bindable: true
    tags: [redis32, redis, key-value]
    metadata:
      displayName: 'Redis 3.2'
      longDescription: 'A Redis 2.8 service for development and testing running inside a Docker container'
      providerDisplayName: 'Cloud Foundry Community'
      documentationUrl: 'https://github.com/frodenas/docker-redis'
      supportUrl: 'https://slack.cloudfoundry.org'
    plans:
    - id: '13d21792-14f5-11e7-81cd-4357fa4eeda9'
      name: 'free'
      description: 'Free Trial'
      container:
        backend: 'docker'
        image: 'frodenas/redis'
        tag: '3.2'
        persistent_volumes: [/data]
      credentials:
        password: {key: 'REDIS_PASSWORD'}

assets:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
